-- Flyway corre esto al arrancar la app. Las migraciones siguientes van como
-- V2__descripcion.sql, V3__... — nunca se edita una ya aplicada.
CREATE TABLE items (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
