-- Módulo IA. Necesita pgvector, que viene en la imagen docker/postgres.
-- Si desactivás el módulo (`modules.ai.enabled=false`) esta migración igual
-- corre: para sacarlo del todo, borrá el paquete `ai` y este archivo.
CREATE EXTENSION IF NOT EXISTS vector;

-- Historial del chat. Sin tabla de conversaciones aparte: el id lo genera el
-- back en el primer mensaje y agrupa; una tabla menos que mantener.
CREATE TABLE ai_messages (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id UUID        NOT NULL,
    role            TEXT        NOT NULL CHECK (role IN ('system', 'user', 'assistant')),
    content         TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ai_messages_conversation_idx ON ai_messages (conversation_id, id);

-- Los pedazos de documento del RAG con su embedding.
-- OJO: 1024 es la dimensión de BAAI/bge-m3 (el modelo por defecto). Si cambiás
-- `ai.deepinfra.embedding-model` por uno de otra dimensión, hace falta una
-- migración nueva que altere el tipo: pgvector no acepta vectores de otro largo.
CREATE TABLE ai_chunks (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_title TEXT        NOT NULL,
    content        TEXT        NOT NULL,
    embedding      VECTOR(1024) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ai_chunks_document_idx ON ai_chunks (document_title);

-- HNSW para búsqueda por coseno: sin índice, cada pregunta escanea la tabla
-- entera. Con pocos documentos no se nota; con 50k chunks sí.
CREATE INDEX ai_chunks_embedding_idx ON ai_chunks USING hnsw (embedding vector_cosine_ops);
