-- Módulo geovisor. Necesita PostGIS, que viene en la imagen docker/postgres.
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE geo_features (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    category   TEXT        NOT NULL DEFAULT 'default',
    -- Geometry y no Point: así la misma tabla guarda puntos, líneas y polígonos.
    -- 4326 es WGS84, o sea lat/lon de toda la vida, que es lo que habla Leaflet.
    geom       geometry(Geometry, 4326) NOT NULL,
    properties JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Índice espacial: sin esto, filtrar por bbox lee la tabla entera.
CREATE INDEX geo_features_geom_idx ON geo_features USING GIST (geom);
CREATE INDEX geo_features_category_idx ON geo_features (category);

-- Datos de ejemplo para que el mapa no arranque vacío. Borralos cuando metas
-- los tuyos: DELETE FROM geo_features WHERE category = 'demo';
INSERT INTO geo_features (name, category, geom, properties) VALUES
    ('Plaza de Bolívar', 'demo', ST_SetSRID(ST_MakePoint(-74.0765, 4.5981), 4326), '{"ciudad":"Bogotá"}'),
    ('Monserrate',       'demo', ST_SetSRID(ST_MakePoint(-74.0556, 4.6058), 4326), '{"altura_m":3152}'),
    ('Universidad Distrital', 'demo', ST_SetSRID(ST_MakePoint(-74.0817, 4.6286), 4326), '{"sede":"Macarena"}'),
    ('Corredor Séptima', 'demo',
     ST_SetSRID(ST_GeomFromText('LINESTRING(-74.0721 4.5981, -74.0637 4.6486)'), 4326), '{"tipo":"vía"}');
